### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by parmentelat** [apowers313/magicpatch#3]
Hi
thanks for coming up with this tool, on the paper that's exactly what I am looking for !

I can't seem to install it though; I am under macos, and in case it is relevant have jupyter installed inside a miniconda

I had `ijs` already installed (globally though, I don't know, but would love to known, how to npm install locally to a miniconda, another matter entirely..)

but I still did the following, assuming it would override my ijs install
```
npm install -g magicpatch
ijsinstall --startup-script=$(magicpatch-location)
```

at which point I restarted my kernel from the jupyter menus; but trying to run a cell with

```
%echo hello
```

still yields

```
evalmachine.<anonymous>:1
%echo jsdhkfj
^

SyntaxError: Unexpected token '%'
```

and I am not quite sure how to troubleshoot that

**Comment by apowers313** [comment]
Thanks for the note, I haven't  tried with miniconda before but we should be able to figure this out pretty quick.

It looks like magicpatch isn't being installed as a startup script (the error you are getting is what  you would see if magicpatch isn't installed).

To help debug, can you do this and send the  output:
``` bash
npm install -g envinfo
envinfo
```

Here are some debugging tricks:
1. In your terminal type `magicpatch-location` to verify that magicpatch is installed globally. Mine shows `/Users/ampower/Projects/personal/magicpatch/index.js`
2. In your terminal type `jupyter kernelspec list`. Mine shows `javascript    /Users/ampower/Library/Jupyter/kernels/javascript`
3. In your terminal type `cat /Users/ampower/Library/Jupyter/kernels/javascript/kernel.json` (note: substitute your path in that command). The file should include something like "--startup-script=/Users/ampower/Projects/personal/magicpatch/index.js", which loads magicpatch on startup.
4. In your Jupyter notebook type `global.__magicpatchInternal`, which should show a bunch of symbols. If that command doesn't show any output, magicpatch isn't loaded.

![image](https://user-images.githubusercontent.com/5661534/108606270-fee54580-736d-11eb-8bdb-065dc4890420.png)

I can help you figure out where to go next depending on which command above doesn't work or doesn't look right.

**Comment by parmentelat** [comment]
hi; thanks for the feedback

envinfo's output is this
```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 522.44 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.5.3 - /usr/local/bin/npm
  Managers:
    Cargo: 1.29.0 - ~/.cargo/bin/cargo
    CocoaPods: 1.10.1 - /usr/local/bin/pod
    Homebrew: 2.7.5 - /usr/local/bin/brew
    pip3: 20.3.3 - ~/miniconda3/envs/ue22-web-intro/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    CMake: 3.18.4 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 10.15. - /usr/bin/gcc
    Git: 2.26.2 - /usr/local/bin/git
    Clang: 1200.0.32.29 - /usr/bin/clang
    FFmpeg: 4.3.1 - /usr/local/bin/ffmpeg
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    VirtualBox: 6.1.16 - /usr/local/bin/vboxmanage
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  IDEs:
    Atom: 1.50.0
    Emacs: 27.1 - /usr/local/bin/emacs
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.53.2 - /usr/local/bin/code
    Vim: 8.1 - /usr/bin/vim
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Bash: 5.0.17 - /usr/local/bin/bash
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Protoc: 3.12.2 - /usr/local/bin/protoc
    Python: 3.8.5 - /Users/tparment/miniconda3/envs/ue22-web-intro/bin/python
    Python3: 3.8.5 - /Users/tparment/miniconda3/envs/ue22-web-intro/bin/python3
    R: 3.6.1 - /usr/local/bin/R
    Ruby: 2.6.3 - /usr/bin/ruby
    Rust: 1.29.1 - /Users/tparment/.cargo/bin/rustc
  Databases:
    SQLite: 3.33.0 - /Users/tparment/miniconda3/envs/ue22-web-intro/bin/sqlite3
  Browsers:
    Chrome: 88.0.4324.182
    Firefox: 85.0.2
    Safari: 14.0.3
```

and then

```bash
$ magicpatch-location
/usr/local/lib/node_modules/magicpatch/index.js
```

```bash
$ jupyter kernelspec list
Available kernels:
  python3         /Users/tparment/miniconda3/envs/ue22-web-intro/share/jupyter/kernels/python3
  javascript      /Users/tparment/Library/Jupyter/kernels/javascript
  calysto_bash    /usr/local/share/jupyter/kernels/calysto_bash
```

```bash
$ cat /Users/tparment/Library/Jupyter/kernels/javascript/kernel.json
{"argv":["ijskernel","--show-undefined","{connection_file}","--protocol=5.1"],"display_name":"Javascript (Node.js)","language":"javascript"}
```

```javascript
In [7]: global.__magicpatchInternal
Out[7]: undefined
```

and also just in case

```bash 
$ ijs --version
5.2.0
```

thanks !

**Comment by apowers313** [comment]
Interesting, the startup script didn’t get installed in your `kernel.json` or that file got reverted back to the original (there is no `—startup-script` in that file).

Suggested next steps:
1. Run `ijsinstall --startup-script=/usr/local/lib/node_modules/magicpatch/index.js`
2. Edit `/Users/tparment/Library/Jupyter/kernels/javascript/kernel.json` to make sure it has `—startup-script=/usr/local/lib/node_modules/magicpatch/index.js` in the `argv` array. If it doesn't, add it by hand.
3. Fire up Jupyter and try `global.__magicpatchInternal` again.
4. Check and see if your `kernel.json` is the same as before.

Here's my `kernel.json` for reference:
``` json
{
    "argv": [
        "ijskernel",
        "--startup-script=/Users/ampower/Projects/personal/magicpatch/index.js",
        "--hide-undefined",
        "{connection_file}",
        "--protocol=5.1"
    ],
    "display_name": "Javascript (Node.js)",
    "language": "javascript"
}
```

**Comment by apowers313** [comment]
Also, I just published magicpatch  0.12.0 which has a new `magicpatch-install` command.  You can try that for updating your kernel spec if you want.

**Comment by parmentelat** [comment]
it's quite odd, and I feel a bit of a fool, because after following your instructions everything went fine, and the magic gets expanded as expected; I have not yet upgraded `magicpatch` at this point - (but I will shortly of course :)

so... let me not bother you any longer, I guess I just did something wrong the first time, in any case I'm good for now :)

thanks !

**Comment by apowers313** [comment]
No worries! Closing this for now, but feel free to reopen if you have any problems. :)
