### ISSUE TITLE
Add an %async% magic to run the cell asyncronically

### ISSUE THREAD

**Issue by wei3erHase** [apowers313/magicpatch#69]
A big downside of JS on Jupyter is that some instructions are run at the same time in Node, so we had to tweak a solution that would be great to have with magic commands:

```js
const next = async (fn) => {
  previous = previous ? previous.then(() => fn()) : fn();
  previous.catch((err) => {
    console.error(err);
    previous = null;
  });
```

![image](https://user-images.githubusercontent.com/84595958/128213753-4a3197c1-cdf0-4e0c-bb3c-45d732bdb976.png)
![image](https://user-images.githubusercontent.com/84595958/128213976-c281412a-b5f7-4955-ba09-7ff627e15e26.png)

In that way, one could call 'Run all cells' and code would run smoothly when interacting with promises.

**Comment by apowers313** [comment]
I'm not sure I'm following the request. If the result of a cell is a Promise, the cell will wait for the resolution of the Promise before proceeding. Conversely, if the result of a cell is not a Promise, the code will execute in the interpreter and control will return to the Jupyter front end.

**Comment by wei3erHase** [comment]
In that way one could set first the non asyncronyc inputs (constants), and with the use of magic commands (like `%%async`) would run the cells in order. Not starting next block until promise of the previous block has been resolved.
It gets really handy when interacting with the blockchain, as each block could represent a set of transactions.
We're achieveng it by the `next(async() =>{}) ` contraption.
Would it be possible to replicate that code through magic commands syntax?

**Comment by apowers313** [comment]
Got it. There's a cheap hacky way to do it -- just end your cell with a statement that doesn't return a promise (e.g. `true`, `1`, `;`, `console.log()`, ...).

If you want to implement it the right way use `$$.addMagic()` ([details here](https://github.com/apowers313/magicpatch/blob/master/AddingMagics.md)). Something like this might work (untested code):
``` js
global.$$.addMagic("async", {
  fn: myAsyncEvalFn,
  brief: "Evaluates code asynchronously -- doesn't resolve promises",
  cellMagic: true,
});

function myAsyncEvalFn(cmd, code) {
  // run code with magic interpretation (e.g. parse out '%' commands from code):
  let res = vm.runInThisContext(code);

  // ...or run code WITHOUT magicpatch interpretation (i.e. treat as normal javascript):
  let res = global.__magicpatchInternal.origVmRunInThisContext(code);

  // don't do both, that would be silly ;)
}
```

Hope that helps. Feel free to submit a pull request if you want`%%async` to be available to everyone.

**Comment by apowers313** [comment]
Feel free to re-open this if you need more help.
